---
- hosts: database
  become: true
  tasks:
            
          - name: "Copy repo"
            copy:
                    src: ./mongodb-org-4.4.repo
                    dest: /etc/yum.repos.d
                    owner: root
                    group: wheel
                    mode: '0644'

          - name: "Install MongoDB"
            yum:
                    name: mongodb-org
                    state: present

          - name: Mongo configuration 
            template:
                   src: templates/mongod.conf.j2
                   dest: /etc/mongod.conf
                   owner: root
                   group: wheel
                   mode: '0644'

          
          - name: "Start MongoDB"
            service:
                    name: mongod
                    state: started
                    enabled: yes
