---
- hosts: webserver
  become: true
  pre_tasks:
    - name: install pip
      yum: name=python3-pip state=latest
    
  tasks:
    - name: Install flask
      shell: pip3 install Flask
    - name: Install Werkzeug
      shell: pip3 install Werkzeug
    - name: "Moving the web file"
      copy:
        src: templates/templates
        dest: /home/vagrant
        mode: 0755
    - name: "Moving the python file"
      copy:
        src: templates/webserver.py
        dest: /home/vagrant
        mode: 0755
    - name: Run python server
      shell: "(sudo python3 /home/vagrant/webserver.py >/dev/null 2>&1 &)"
      async: 45
      poll: 0
    - name: Install pymongo
      shell: pip3 install pymongo
    - name: Install Flask-PyMongo
      shell: pip3 install Flask-PyMongo
    - name: Install waitress
      shell: pip3 install waitress 
 

